// <copyright file="Achievements.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to achievements registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Achievements
    {
        private static readonly UnifiedAchievement s_score10k = new UnifiedAchievement("score10k",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIt4rVipEeEAIQAg"
#else
            "score10k"
#endif
            );

        public static UnifiedAchievement score10k
        {
            get { return s_score10k; }
        }

        private static readonly UnifiedAchievement s_score35k = new UnifiedAchievement("score35k",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIt4rVipEeEAIQAw"
#else
            "score35k"
#endif
            );

        public static UnifiedAchievement score35k
        {
            get { return s_score35k; }
        }

        private static readonly UnifiedAchievement s_score50k = new UnifiedAchievement("score50k",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIt4rVipEeEAIQBA"
#else
            "score50k"
#endif
            );

        public static UnifiedAchievement score50k
        {
            get { return s_score50k; }
        }

        private static readonly UnifiedAchievement s_score100k = new UnifiedAchievement("score100k",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIt4rVipEeEAIQBQ"
#else
            "score100k"
#endif
            );

        public static UnifiedAchievement score100k
        {
            get { return s_score100k; }
        }

        private static readonly UnifiedAchievement s_destroy50enemies = new UnifiedAchievement("destroy50enemies",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIt4rVipEeEAIQBg"
#else
            "destroy50enemies"
#endif
            );

        public static UnifiedAchievement destroy50enemies
        {
            get { return s_destroy50enemies; }
        }

        private static readonly UnifiedAchievement s_destroy150enemies = new UnifiedAchievement("destroy150enemies",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIt4rVipEeEAIQBw"
#else
            "destroy150enemies"
#endif
            );

        public static UnifiedAchievement destroy150enemies
        {
            get { return s_destroy150enemies; }
        }

        private static readonly UnifiedAchievement s_collect25powerup = new UnifiedAchievement("collect25powerup",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIt4rVipEeEAIQCA"
#else
            "collect25powerup"
#endif
            );

        public static UnifiedAchievement collect25powerup
        {
            get { return s_collect25powerup; }
        }

        private static readonly UnifiedAchievement s_collect50powerup = new UnifiedAchievement("collect50powerup",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIt4rVipEeEAIQCQ"
#else
            "collect50powerup"
#endif
            );

        public static UnifiedAchievement collect50powerup
        {
            get { return s_collect50powerup; }
        }

        private static readonly UnifiedAchievement s_destroy300enemies = new UnifiedAchievement("destroy300enemies",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIt4rVipEeEAIQCg"
#else
            "destroy300enemies"
#endif
            );

        public static UnifiedAchievement destroy300enemies
        {
            get { return s_destroy300enemies; }
        }

        private static readonly UnifiedAchievement s_score300k = new UnifiedAchievement("score300k",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIt4rVipEeEAIQCw"
#else
            "score300k"
#endif
            );

        public static UnifiedAchievement score300k
        {
            get { return s_score300k; }
        }

        public static readonly UnifiedAchievement[] All =
        {
            s_score10k,
            s_score35k,
            s_score50k,
            s_score100k,
            s_destroy50enemies,
            s_destroy150enemies,
            s_collect25powerup,
            s_collect50powerup,
            s_destroy300enemies,
            s_score300k,
        };

        public static string GetPlatformID(string internalId)
        {
            return s_achievementDictionary.ContainsKey(internalId)
                ? s_achievementDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedAchievement> s_achievementDictionary = new Dictionary<string, UnifiedAchievement>
        {
            { "score10k", s_score10k },
            { "score35k", s_score35k },
            { "score50k", s_score50k },
            { "score100k", s_score100k },
            { "destroy50enemies", s_destroy50enemies },
            { "destroy150enemies", s_destroy150enemies },
            { "collect25powerup", s_collect25powerup },
            { "collect50powerup", s_collect50powerup },
            { "destroy300enemies", s_destroy300enemies },
            { "score300k", s_score300k },
        };
    }
}
